name: swan
description: bring elegance to your flutter discussions
version: 1.0.0
repository: https://github.com/clragon/swan

environment:
  sdk: ^3.8.0

dependencies:
  collection: ^1.19.1
  dart_style: ^3.1.0
  dotenv: ^4.2.0
  drift: ^2.25.1
  freezed_annotation: ^3.1.0
  http: ^1.3.0
  json_annotation: ^4.9.0
  nyxx: ^6.6.0
  nyxx_extensions: ^4.3.0
  petitparser: ^7.0.0
  recase: ^4.1.0
  timeago: ^3.7.0

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.25.2
  freezed: ^3.1.0
  json_serializable: ^6.9.0
  lints: ^6.0.0
  test: ^1.25.15
