name: swan
description: bring elegance to your flutter discussions
version: 1.0.0
repository: https://github.com/clragon/swan

environment:
  sdk: ^3.1.0

dependencies:
  analyzer: ^6.11.0
  collection: ^1.19.1
  dart_style: ^2.3.8
  dotenv: ^4.2.0
  drift: ^2.25.1
  freezed_annotation: ^2.4.4
  http: ^1.3.0
  intl: ^0.18.1
  json_annotation: ^4.9.0
  logging: ^1.3.0
  meta: ^1.16.0
  nyxx: ^6.6.0
  nyxx_extensions: ^4.3.0
  petitparser: ^6.1.0
  recase: ^4.1.0
  timeago: ^3.7.0

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.25.2
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  lints: ^3.0.0
  test: ^1.25.15
